### ISSUE TITLE
[Question] Which printer settings to use?

### ISSUE THREAD

**Issue by Gamer2020** [arpruss/miscellaneous-scad#1]
Hi. I found your settings along my quest to set up my Davinci 1.0a.

Which one of your settings should I be using?

![image](https://user-images.githubusercontent.com/6243575/50389017-1a9f2380-06f2-11e9-8b9e-41c72aa0672d.png)

**Comment by arpruss** [comment]
I am afraid thee is no easy answer. It depends on the materials and the print. That said, I've been happy with the DaVinci1.0a -.1.ini file for most prints lately.

**Comment by Gamer2020** [comment]
Understood. Thank you!
